// Nepal administrative data structure
// This is a simplified version with some example data

export const nepalData = [
  {
    name: "Bagmati Pradesh",
    districts: [
      {
        name: "Kathmandu",
        municipalities: [
          { name: "Kathmandu Metropolitan City" },
          { name: "Kirtipur Municipality" },
          { name: "Gokarneshwor Municipality" },
          { name: "Chandragiri Municipality" },
          { name: "Tokha Municipality" },
          { name: "Tarakeshwor Municipality" },
          { name: "Dakshinkali Municipality" },
          { name: "Nagarjun Municipality" },
          { name: "Kageshwori-Manohara Municipality" },
          { name: "Shankharapur Municipality" },
          { name: "Budhanilkantha Municipality" },
        ],
      },
      {
        name: "Lalitpur",
        municipalities: [
          { name: "Lalitpur Metropolitan City" },
          { name: "Godawari Municipality" },
          { name: "Mahalaxmi Municipality" },
          { name: "Konjyosom Rural Municipality" },
          { name: "Bagmati Rural Municipality" },
          { name: "Mahankaal Rural Municipality" },
        ],
      },
      {
        name: "Bhaktapur",
        municipalities: [
          { name: "Bhaktapur Municipality" },
          { name: "Madhyapur Thimi Municipality" },
          { name: "Suryabinayak Municipality" },
          { name: "Changunarayan Municipality" },
        ],
      },
      {
        name: "Chitwan",
        municipalities: [
          { name: "Bharatpur Metropolitan City" },
          { name: "Ratnanagar Municipality" },
          { name: "Khairahani Municipality" },
          { name: "Madi Municipality" },
          { name: "Kalika Municipality" },
          { name: "Rapti Municipality" },
          { name: "Ichchhakamana Rural Municipality" },
        ],
      },
    ],
  },
  {
    name: "Gandaki Pradesh",
    districts: [
      {
        name: "Kaski",
        municipalities: [
          { name: "Pokhara Metropolitan City" },
          { name: "Annapurna Rural Municipality" },
          { name: "Machhapuchhre Rural Municipality" },
          { name: "Madi Rural Municipality" },
          { name: "Rupa Rural Municipality" },
        ],
      },
      {
        name: "Tanahun",
        municipalities: [
          { name: "Bhanu Municipality" },
          { name: "Bhimad Municipality" },
          { name: "Byas Municipality" },
          { name: "Shuklagandaki Municipality" },
          { name: "Myagde Rural Municipality" },
          { name: "Rhishing Rural Municipality" },
          { name: "Ghiring Rural Municipality" },
          { name: "Devghat Rural Municipality" },
          { name: "Bandipur Rural Municipality" },
          { name: "Aanbookhaireni Rural Municipality" },
        ],
      },
    ],
  },
  {
    name: "Province 1",
    districts: [
      {
        name: "Jhapa",
        municipalities: [
          { name: "Mechinagar Municipality" },
          { name: "Birtamod Municipality" },
          { name: "Damak Municipality" },
          { name: "Kankai Municipality" },
          { name: "Bhadrapur Municipality" },
          { name: "Arjundhara Municipality" },
          { name: "Shivasatakshi Municipality" },
          { name: "Gauradaha Municipality" },
          { name: "Buddhashanti Rural Municipality" },
          { name: "Haldibari Rural Municipality" },
          { name: "Kachankawal Rural Municipality" },
          { name: "Jhapa Rural Municipality" },
          { name: "Barhadashi Rural Municipality" },
          { name: "Gaurigunj Rural Municipality" },
          { name: "Kamal Rural Municipality" },
        ],
      },
      {
        name: "Morang",
        municipalities: [
          { name: "Biratnagar Metropolitan City" },
          { name: "Sundarharaicha Municipality" },
          { name: "Rangeli Municipality" },
          { name: "Pathari-Shanishchare Municipality" },
          { name: "Urlabari Municipality" },
          { name: "Sunawarshi Municipality" },
          { name: "Ratuwamai Municipality" },
          { name: "Letang Municipality" },
          { name: "Budhiganga Rural Municipality" },
          { name: "Dhanpalthan Rural Municipality" },
          { name: "Gramthan Rural Municipality" },
          { name: "Jahada Rural Municipality" },
          { name: "Kanepokhari Rural Municipality" },
          { name: "Katahari Rural Municipality" },
          { name: "Kerabari Rural Municipality" },
          { name: "Miklajung Rural Municipality" },
          { name: "Sunwarshi Rural Municipality" },
        ],
      },
    ],
  },
  {
    name: "Madhesh Pradesh",
    districts: [
      {
        name: "Parsa",
        municipalities: [
          { name: "Birgunj Metropolitan City" },
          { name: "Bahudarmai Municipality" },
          { name: "Parsagadhi Municipality" },
          { name: "Pokhariya Municipality" },
          { name: "Bindabasini Rural Municipality" },
          { name: "Dhobini Rural Municipality" },
          { name: "Chhipaharmai Rural Municipality" },
          { name: "Jagarnathpur Rural Municipality" },
          { name: "Jirabhawani Rural Municipality" },
          { name: "Kalikamai Rural Municipality" },
          { name: "Pakaha Mainpur Rural Municipality" },
          { name: "Paterwa Sugauli Rural Municipality" },
          { name: "Sakhuwa Prasauni Rural Municipality" },
          { name: "Thori Rural Municipality" },
        ],
      },
      {
        name: "Bara",
        municipalities: [
          { name: "Kalaiya Sub-Metropolitan City" },
          { name: "Jeetpur Simara Sub-Metropolitan City" },
          { name: "Kolhabi Municipality" },
          { name: "Nijgadh Municipality" },
          { name: "Mahagadhimai Municipality" },
          { name: "Simraungadh Municipality" },
          { name: "Pacharauta Municipality" },
          { name: "Adarsh Kotwal Rural Municipality" },
          { name: "Baragadhi Rural Municipality" },
          { name: "Devtal Rural Municipality" },
          { name: "Karaiyamai Rural Municipality" },
          { name: "Parwanipur Rural Municipality" },
          { name: "Pheta Rural Municipality" },
          { name: "Prasauni Rural Municipality" },
          { name: "Suwarna Rural Municipality" },
          { name: "Bishrampur Rural Municipality" },
        ],
      },
    ],
  },
  {
    name: "Lumbini Pradesh",
    districts: [
      {
        name: "Rupandehi",
        municipalities: [
          { name: "Butwal Sub-Metropolitan City" },
          { name: "Siddharthanagar Municipality" },
          { name: "Lumbini Sanskritik Municipality" },
          { name: "Devdaha Municipality" },
          { name: "Sainamaina Municipality" },
          { name: "Tilottama Municipality" },
          { name: "Gaidahawa Rural Municipality" },
          { name: "Kanchan Rural Municipality" },
          { name: "Kotahimai Rural Municipality" },
          { name: "Marchawari Rural Municipality" },
          { name: "Mayadevi Rural Municipality" },
          { name: "Omsatiya Rural Municipality" },
          { name: "Rohini Rural Municipality" },
          { name: "Sammarimai Rural Municipality" },
          { name: "Siyari Rural Municipality" },
          { name: "Suddhodhan Rural Municipality" },
        ],
      },
      {
        name: "Kapilvastu",
        municipalities: [
          { name: "Kapilvastu Municipality" },
          { name: "Banganga Municipality" },
          { name: "Buddhabhumi Municipality" },
          { name: "Shivaraj Municipality" },
          { name: "Maharajgunj Municipality" },
          { name: "Krishnanagar Municipality" },
          { name: "Mayadevi Rural Municipality" },
          { name: "Suddhodhan Rural Municipality" },
          { name: "Yasodhara Rural Municipality" },
          { name: "Bijaynagar Rural Municipality" },
        ],
      },
    ],
  },
  {
    name: "Karnali Pradesh",
    districts: [
      {
        name: "Surkhet",
        municipalities: [
          { name: "Birendranagar Municipality" },
          { name: "Bheriganga Municipality" },
          { name: "Gurbhakot Municipality" },
          { name: "Panchapuri Municipality" },
          { name: "Lekbeshi Municipality" },
          { name: "Chaukune Rural Municipality" },
          { name: "Barahatal Rural Municipality" },
          { name: "Chingad Rural Municipality" },
          { name: "Simta Rural Municipality" },
        ],
      },
      {
        name: "Dailekh",
        municipalities: [
          { name: "Narayan Municipality" },
          { name: "Dullu Municipality" },
          { name: "Chamunda Bindrasaini Municipality" },
          { name: "Aathbis Municipality" },
          { name: "Bhagawatimai Rural Municipality" },
          { name: "Gurans Rural Municipality" },
          { name: "Dungeshwar Rural Municipality" },
          { name: "Naumule Rural Municipality" },
          { name: "Mahabu Rural Municipality" },
          { name: "Thantikandh Rural Municipality" },
          { name: "Bhairabi Rural Municipality" },
        ],
      },
    ],
  },
  {
    name: "Sudurpashchim Pradesh",
    districts: [
      {
        name: "Kailali",
        municipalities: [
          { name: "Dhangadhi Sub-Metropolitan City" },
          { name: "Tikapur Municipality" },
          { name: "Godawari Municipality" },
          { name: "Gauriganga Municipality" },
          { name: "Ghodaghodi Municipality" },
          { name: "Lamkichuha Municipality" },
          { name: "Bhajani Municipality" },
          { name: "Janaki Rural Municipality" },
          { name: "Bardagoriya Rural Municipality" },
          { name: "Mohanyal Rural Municipality" },
          { name: "Kailari Rural Municipality" },
          { name: "Joshipur Rural Municipality" },
          { name: "Chure Rural Municipality" },
        ],
      },
      {
        name: "Kanchanpur",
        municipalities: [
          { name: "Bhimdatta Municipality" },
          { name: "Punarbas Municipality" },
          { name: "Bedkot Municipality" },
          { name: "Belauri Municipality" },
          { name: "Krishnapur Municipality" },
          { name: "Mahakali Municipality" },
          { name: "Shuklaphanta Municipality" },
          { name: "Beldandi Rural Municipality" },
          { name: "Laljhadi Rural Municipality" },
        ],
      },
    ],
  },
]
